### ISSUE TITLE
Implement minimal downtime on Postcode API

### ISSUE THREAD

**Issue by KamalaHB** [ministryofjustice/postcodeinfo#100]

**Comment by KamalaHB** [comment]
Minimal downtime deploy on production.

**Comment by aldavidson** [comment]
Closing this, as we now have:
* -deploy repo updated to latest template-deploy
* 2 staging and 2 production stacks 
...so we can now deploy to the parallel stack and then swap the DNS entry, achieving pretty-much zero-downtime
