### ISSUE TITLE
Partial requests fail due to timeouts (32 seconds)

### ISSUE THREAD

**Issue by ltsampros** [ministryofjustice/postcodeinfo#124]
Partial requests seem to be causing a rather large database load that lead to 502 errors due to connection timeouts.

After a discussion with Alistair we decided that partitioning the table based on the first characters of the postcode itself. This is a PostgreSQL specific feature.

This functionality can be enabled/achieved through Django transparently using the [Architect library](http://architect.readthedocs.org/index.html)

**Comment by aldavidson** [comment]
I've looked into this, and found that although creating the partition tables & triggers is pretty straightforward with architect, the highly-optimised addressbase import job will need to be heavily modified.

The import job currently imports all files into a temp table, INSERT..SELECTs from there into an offline table created on-demand with no indexes, and then once complete, creates the indexes, and finally swaps the names of the live and offline tables in one transaction. This way, it can run in single-digit hours, with only a sub-second impact on the live table at the end.

Unfortunately this doesn't work with the architect triggers, as they're only defined for insert & delete operations on the live table. I need to re-think this process at a fundamental level, as it appears we have a big trade-off to make between run-time performance and import performance.
