### ISSUE TITLE
Try given postcode as partial postcode if no results

### ISSUE THREAD

**Issue by andyhd** [ministryofjustice/postcodeinfo#87]
Instead of providing a separate endpoint for looking up partial postcodes, I think the postcode parameter should be retried as a partial postcode if there are no results for the full postcode lookup.

The code [here](https://github.com/ministryofjustice/postcodeinfo/blob/master/postcodeinfo/apps/postcode_api/views.py#L50) could be updated like this:
```python
def __get_geometry(self, postcode):
    geom = Address.objects.filter(
        **{'postcode_index': postcode}).collect(field_name='point')
    if not geom:
        geom = Address.objects.filter(
            **{'postcode_area': postcode}).collect(field_name='point')
    return geom
```
The response would also need to indicate whether it was a full or partial match.

**Comment by aldavidson** [comment]
Don't think we need this now that we have established workable partial search endpoints - it's better to keep them separate
